model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/qwen-flash
      api_base: http://127.0.0.1:8011/v1
      api_key: none
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/qwen-flash
      api_base: http://127.0.0.1:8011/v1
      api_key: none
  - model_name: qwen-flash
    litellm_params:
      model: openai/qwen-flash
      api_base: http://127.0.0.1:8011/v1
      api_key: none
  - model_name: gpt-4o
    litellm_params:
      model: openai/qwen3-coder-next
      api_base: http://127.0.0.1:8014/v1
      api_key: none
  - model_name: qwen3.6
    litellm_params:
      model: openai/qwen3.6
      api_base: http://127.0.0.1:8014/v1
      api_key: none
  - model_name: gemma-4
    litellm_params:
      model: openai/gemma-4
      api_base: http://127.0.0.1:8012/v1
      api_key: none
    model_info:
      base_model: gemma-4
      fallback_models: ["qwen-flash"]

litellm_settings:
  drop_params: true
  modify_params: true
  set_verbose: false
  cors_allow_origins: ["*"]
  cache: true
  cache_params:
    cache_type: local

router_settings:
  routing_strategy: latency-based-routing
  enable_pre_call_checks: true
