model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: qwen-flash
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: qwen3-coder-next
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: gpt-oss-120b
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
    model_info:
      max_tokens: 65536
      input_cost_per_token: 0.0
      output_cost_per_token: 0.0
  - model_name: qwq-32b
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://127.0.0.1:8013/v1
      api_key: none
litellm_settings:
  drop_params: true
  set_verbose: true
router_settings:
  routing_strategy: simple-shuffle
